version: '3.7'

services:
  polaris:
    image: junofx/polaris:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PAS=nom-nom()
      - USR=testing
      - RES=1920x1080
    ports:
      - 5901:5901

  no-vnc:
    image: dougw/novnc
    environment:
      - REMOTE_PORT=5901
      - REMOTE_HOST=polaris
    ports:
      - 8081:8081
